### ISSUE TITLE
Issue with `super` and `alias`

### ISSUE THREAD

**Issue by richardboehme** [seven1m/natalie#81]
When using `super` in an aliased method natalie crashes.

Example:
```ruby
module Base
  def chunk
    puts "called Base#chunk"
  end
end


class Child
  include Base

  def chunk
    puts "called Child#chunk"
    super
  end
  alias chunk_while chunk
end

p Child.new.chunk_while
```

Ruby output:
```
called Child#chunk
called Base#chunk
nil
```

Natalie output:
```
called Child#chunk
Traceback (most recent call last):
        1: from example.rb:18:in `<main>'
example.rb:12:in `chunk': super: no superclass method `chunk' for #<Child:0x55f253565120> (NoMethodError)
```

Instead of a module we can also use `Base` as a super class to `Child`.

**Comment by seven1m** [comment]
Fixed in 753b88482d31164d345f3d34527c70f3d9e0b3aa
